<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UnityTargetFramework Condition="'$(UnityTargetFramework)' == ''">net9.0</UnityTargetFramework>
        <TargetFramework>$(UnityTargetFramework)</TargetFramework>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishSelfContained>true</PublishSelfContained>
        <DebugType>none</DebugType>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>unity-hub-launcher</AssemblyName>
        <RootNamespace>Unity.UnityHub</RootNamespace>
    </PropertyGroup>
</Project>
